name: Actionlint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  actionlint:
    name: Actionlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Run actionlint
        uses: raven-actions/actionlint@v2
